### ISSUE TITLE
Error: Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by stefanocudini** [GIScience/openrouteservice-app#343]
I'm recevice this on first installation:
```bash
Running "run_grunt:sliderMakeCss" (run_grunt) task
smartbin-ors-app | --> starting  "bower_components/angularjs-slider/Gruntfile.js"
smartbin-ors-app | --> reporting "bower_components/angularjs-slider/Gruntfile.js"
smartbin-ors-app |   |  Initializing
smartbin-ors-app |   |  Command-line options: --gruntfile=/ors-app/bower_components/angularjs-slider/Gruntfile.js, --debug=1, --verbose
smartbin-ors-app |   |  
smartbin-ors-app |   |  Reading "Gruntfile.js" Gruntfile...OK
smartbin-ors-app |   |  
smartbin-ors-app |   |  Registering Gruntfile tasks.
smartbin-ors-app |   |  Reading package.json...OK
smartbin-ors-app |   |  Parsing package.json...OK
smartbin-ors-app |   |  Loading "Gruntfile.js" tasks...ERROR
smartbin-ors-app |   |  >> Error: Cannot find module 'autoprefixer'
smartbin-ors-app |   |  >>     at Function.Module._resolveFilename (module.js:547:15)
smartbin-ors-app |   |  >>     at Function.Module._load (module.js:474:25)
smartbin-ors-app |   |  >>     at Module.require (module.js:596:17)
smartbin-ors-app |   |  >>     at require (internal/module.js:11:18)
smartbin-ors-app |   |  >>     at Object.module.exports (/ors-app/bower_components/angularjs-slider/Gruntfile.js:163:11)
smartbin-ors-app |   |  >>     at loadTask (/ors-app/node_modules/grunt/lib/grunt/task.js:315:10)
smartbin-ors-app |   |  >>     at Task.task.init (/ors-app/node_modules/grunt/lib/grunt/task.js:450:5)
smartbin-ors-app |   |  >>     at Object.grunt.tasks (/ors-app/node_modules/grunt/lib/grunt.js:129:8)
smartbin-ors-app |   |  >>     at Liftoff.<anonymous> (/usr/local/lib/node_modules/grunt-cli/bin/grunt:66:13)
smartbin-ors-app |   |  >>     at Liftoff.execute (/usr/local/lib/node_modules/grunt-cli/node_modules/liftoff/index.js:203:12)
smartbin-ors-app |   |  
smartbin-ors-app |   |  Running tasks: css
smartbin-ors-app |   |  Warning: Task "css" not found. Use --force to continue.
smartbin-ors-app |   |  
smartbin-ors-app |   |  Aborted due to warnings.
smartbin-ors-app |   |  
smartbin-ors-app | --> failed "bower_components/angularjs-slider/Gruntfile.js" (525ms)
smartbin-ors-app | --> failed sliderMakeCss @ "bower_components/angularjs-slider/Gruntfile.js"
smartbin-ors-app | 
smartbin-ors-app | Warning: 1 gruntfile failed and completed 0 (528ms)
smartbin-ors-app |  Use --force to continue.
smartbin-ors-app | 
smartbin-ors-app | Aborted due to warnings.
smartbin-ors-app | 
smartbin-ors-app | 
smartbin-ors-app | Execution Time (2020-08-18 14:12:20 UTC-0)
smartbin-ors-app | loading tasks            815ms  ▇▇▇▇▇▇▇▇ 21%
smartbin-ors-app | browserify:turf          495ms  ▇▇▇▇▇ 13%
smartbin-ors-app | less:development         166ms  ▇▇ 4%
smartbin-ors-app | prettier:files            1.8s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 48%
smartbin-ors-app | run_grunt:sliderMakeCss  529ms  ▇▇▇▇▇▇ 14%
smartbin-ors-app | Total 3.8s
smartbin-ors-app | 
smartbin-ors-app exited with code 6

```

**Comment by TheGreatRefrigerator** [comment]
Hi @stefanocudini,
Did you do the `npm install` in `bower_components/angular-slider` folder?
which node version are you using?
And which OS are you on?

**Comment by trevorwilf** [comment]
I am having the same issue
npm version: 3.5.2
OS: ubuntu 18.04

I did do the npm install in bower_components/angular-slider  but I get the following error

```
npm ERR! Linux 3.10.0-1062.4.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>
```

**Comment by trevorwilf** [comment]
upgrade my npm to version 6.14.7
this has resolved the issue

**Comment by stefanocudini** [comment]
@trevorwilf  in this way?
```npm install npm@6.14.7 -g```

**Comment by trevorwilf** [comment]
first install the repository:
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -e
then install:
sudo apt-get install -y nodejs

here is some documentation from  the project
https://github.com/nodesource/distributions#debinstall

hope this helps

**Comment by TheGreatRefrigerator** [comment]
@stefanocudini try a node version >=12.
I haven't tried it with 14 yet but seems to work for @trevorwilf .
The npm version should be 6.x, but is included in node >12 anyways.

If you need different node versions for other projects try out [nvm](https://github.com/nvm-sh/nvm)
